apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautible-app-stock
  namespace: argocd
spec:
  destination:
    namespace: nautible-app
    server: https://kubernetes.default.svc
  project: application
  source:
    path: 'overlays/dev/'
    repoURL: https://github.com/nautible/nautible-app-stock-manifest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
