apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: keda
    server: 'https://kubernetes.default.svc'
  source:
    chart: keda
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 2.2.0
    helm:
      version: v3
      releaseName: keda
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
