apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: autoscaler
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/autoscaler/'
    targetRevision: 9.3.0
    chart: cluster-autoscaler
    helm:
      parameters:
        - name: 'autoDiscovery.clusterName'
          value: 'nautible-dev-cluster'
        - name: 'awsRegion'
          value: 'ap-northeast-1'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
