apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- path: patch.json
  target:
    kind: Application
    name: nautible-app-.*

# azure対応が完了したら以下の定義を削除する
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: Application
    name: nautible-app-product
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: Application
    name: nautible-app-payment.*
