apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: dapr-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://dapr.github.io/helm-charts/'
    targetRevision: 1.1.1
    chart: dapr
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
