apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-root
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: application
  source:
    path: 'ArgoCD/secrets/overlays/azure'
    repoURL: https://github.com/nautible/nautible-infra
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true